apiVersion: v2
name: frontend
description: React Frontend Helm Chart for Kubernetes deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - react
  - frontend
  - nginx
  - typescript
maintainers:
  - name: Amin Amrane
    email: aminamrane@example.com

