{{- if not .Values.global.useExternalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "items.fullname" . }}-secret
  labels:
    {{ include "items.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.SECRET_KEY }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.DATABASE_URL }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  {{- end }}
{{- end }}
