global:
  databaseUrl: "postgresql://postgres:postgres@postgres-postgresql.dev.svc.cluster.local:5432/postgres"
  secretKey: "mydevsecret"

auth:
  image:
    repository: aminamr/auth
    tag: dev

users:
  image:
    repository: aminamr/users
    tag: dev

items:
  image:
    repository: aminamr/items
    tag: dev

gateway:
  rateLimit:
    average: 50
    burst: 25
